# I stole this from NotAShelf (raf) get fucked
name: Check Flake Validity

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "**.nix"
      - "**.lock"
      - ".github/workflows/check.yml"
  push:
    paths:
      - "**.nix"
      - "**.lock"
      - ".github/workflows/check.yml"

jobs:
  flake-check-health:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Install nix"
        uses: cachix/install-nix-action@master
        with:
          install_url: "https://nixos.org/nix/install"
          extra_nix_config: |
            experimental-features = nix-command flakes fetch-tree
            allow-import-from-derivation = false

            # nix-community
            extra-substituters = https://nix-community.cachix.org
            extra-trusted-public-keys = nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=

      - name: "Nix Magic Cache"
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: "Perform health checks"
        uses: DeterminateSystems/flake-checker-action@main
